// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlftxyiyackhlqmazopy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sZnR4eWl5YWNraGxxbWF6b3B5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTMxODYsImV4cCI6MjA2MTY2OTE4Nn0.Q7xAYez0x6zeuT1IXgRsZbEdgBaLKE6iHDgoulSgc_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);